# Generated by Django 2.2.6 on 2019-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuneko3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacchaiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('twitter_url', models.URLField()),
            ],
            options={
                'db_table': 'racchai_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='testpic'),
        ),
    ]
