# Generated by Django 2.2.6 on 2020-01-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inuneko3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Image_buttai',
        ),
    ]
