# Generated by Django 2.2.6 on 2019-10-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inuneko3', '0002_auto_20191009_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racchaiuser',
            old_name='email',
            new_name='username',
        ),
    ]
