# Generated by Django 2.2.6 on 2019-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuneko3', '0003_auto_20191009_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racchaiuser',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
